// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdZTKdRKnkKM2GnT90FENELSCmkJx4t2g',
    appId: '1:542419720809:web:5c7a171d5f0f62e3f0a0f8',
    messagingSenderId: '542419720809',
    projectId: 'led-remote-ctrl',
    authDomain: 'led-remote-ctrl.firebaseapp.com',
    storageBucket: 'led-remote-ctrl.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-WgK6xRdfkJxIHn60lqPpENOb9QBJoE8',
    appId: '1:542419720809:android:ef4ee12d8a71d081f0a0f8',
    messagingSenderId: '542419720809',
    projectId: 'led-remote-ctrl',
    storageBucket: 'led-remote-ctrl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9gFeZZ61Sg_6RWSru_6mcfGhxW93LA5Y',
    appId: '1:542419720809:ios:3150decd8bed455df0a0f8',
    messagingSenderId: '542419720809',
    projectId: 'led-remote-ctrl',
    storageBucket: 'led-remote-ctrl.appspot.com',
    iosClientId: '542419720809-ea9sfha6mj19ji1oplntinqsh01re3ba.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9gFeZZ61Sg_6RWSru_6mcfGhxW93LA5Y',
    appId: '1:542419720809:ios:3150decd8bed455df0a0f8',
    messagingSenderId: '542419720809',
    projectId: 'led-remote-ctrl',
    storageBucket: 'led-remote-ctrl.appspot.com',
    iosClientId: '542419720809-ea9sfha6mj19ji1oplntinqsh01re3ba.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );
}
